import 'package:bloc_pattern/bloc_pattern.dart';
import 'package:deshvidesh/home/country.dart';
import 'package:rxdart/subjects.dart';
import 'package:search_app_bar/searcher.dart';

class HomeBloc extends BlocBase implements Searcher<Country> {
  final _filteredData = BehaviorSubject<List<Country>>();

  final dataList = [
    Country(1, 'Afghanistan'),
    Country(2, 'Albania'),
    Country(3, 'Algeria'),
    Country(4, 'Andorra'),
    Country(5, 'Angola'),
    Country(6, 'Antigua and Barbuda'),
    Country(7, 'Argentina'),
    Country(8, 'Armenia'),
    Country(9, 'Australia'),
    Country(10, 'Austria'),
    Country(11, 'Azerbaijan'),
    Country(12, 'Brazil'),
    Country(13, 'Bangladesh'),
    Country(14, 'Burkina Faso'),
    Country(15, 'Benin'),
    Country(16, 'Burundi'),
    Country(17, 'Bolivia'),
    Country(18, 'Belgium'),
    Country(19, 'Belarus'),
    Country(20, 'Bulgaria'),
    Country(21, '	Bosnia and Herzegovina'),
    Country(22, 'Botswana'),
    Country(23, 'Bahrain'),
    Country(24, 'Bhutan'),
    Country(25, 'Brunei'),
    Country(26, 'Belize'),
    Country(27, 'Bahamas'),
    Country(28, 'Barbados'),
    Country(29, 'China'),
    Country(30, 'Colombia'),
    Country(31, 'Canada'),
    Country(32, 'Cameroon'),
    Country(33, 'Côte d\'Ivoire'),
    Country(34, 'Chile'),
    Country(35, 'Cambodia'),
    Country(36, 'Chad'),
    Country(37, 'Cuba'),
    Country(38, 'Czechia (Czech Republic)'),
    Country(39, 'Congo (Congo-Brazzaville)'),
    Country(40, 'Costa Rica'),
    Country(41, 'Central African Republic'),
    Country(42, 'Croatia'),
    Country(43, 'Cyprus'),
    Country(44, 'Comoros'),
    Country(45, 'Cabo Verde'),
    Country(46, 'Democratic Republic of the Congo'),
    Country(47, 'Dominican Republic'),
    Country(48, 'Denmark'),
    Country(49, 'Djibouti'),
    Country(50, 'Dominica'),
    Country(51, 'Ethiopia'),
    Country(52, 'Egypt'),
    Country(53, 'Ecuador'),
    Country(54, 'El Salvador'),
    Country(55, 'Eritrea'),
    Country(56, 'Equatorial Guinea'),
    Country(57, 'Estonia'),
    Country(58, 'Eswatini (fmr. "Swaziland")'),
    Country(59, 'France'),
    Country(60, 'Finland'),
    Country(61, 'Fiji'),
    Country(62, 'Germany'),
    Country(63, 'Ghana'),
    Country(64, 'Guatemala'),
    Country(65, 'Guinea'),
    Country(66, 'Greece'),
    Country(67, 'Georgia'),
    Country(68, 'Gambia'),
    Country(69, 'Gabon'),
    Country(70, 'Guinea-Bissau'),
    Country(71, 'Guyana'),
    Country(72, 'Grenada'),
    Country(73, 'Haiti'),
    Country(74, 'Honduras'),
    Country(75, 'Hungary'),
    Country(76, 'Holy See'),
    Country(77, 'India'),
    Country(78, 'Indonesia'),
    Country(79, 'Iran'),
    Country(80, 'Italy'),
    Country(81, 'Iraq'),
    Country(82, 'Israel'),
    Country(83, 'Ireland'),
    Country(84, 'Iceland'),
    Country(85, 'Japan'),
    Country(86, 'Jordan'),
    Country(87, 'Jamaica'),
    Country(88, 'Kenya'),
    Country(89, 'Kazakhstan'),
    Country(90, 'Kyrgyzstan'),
    Country(91, 'Kuwait'),
    Country(92, 'Kiribati'),
    Country(93, 'Laos'),
    Country(94, 'Libya'),
    Country(95, 'Lebanon'),
    Country(96, 'Liberia'),
    Country(97, 'Lithuania'),
    Country(98, 'Lesotho'),
    Country(99, 'Latvia'),
    Country(100, 'Luxembourg'),
    Country(101, 'Liechtenstein'),
    Country(102, 'Mexico'),
    Country(103, 'Myanmar (formerly Burma)'),
    Country(104, 'Morocco'),
    Country(105, 'Malaysia'),
    Country(106, 'Mozambique'),
    Country(107, 'Madagascar'),
    Country(108, 'Mali'),
    Country(109, 'Malawi'),
    Country(110, 'Mauritania'),
    Country(111, 'Moldova'),
    Country(112, 'Mongolia'),
    Country(113, 'Mauritius'),
    Country(114, 'Montenegro'),
    Country(115, 'Maldives'),
    Country(116, 'Malta'),
    Country(117, 'Micronesia'),
    Country(118, 'Marshall Islands'),
    Country(119, 'Monaco'),
    Country(120, 'Nigeria'),
    Country(121, 'Nepal'),
    Country(122, 'North Korea'),
    Country(123, 'Niger'),
    Country(124, 'Netherlands'),
    Country(125, 'Nicaragua'),
    Country(126, 'Norway'),
    Country(127, 'New Zealand'),
    Country(128, 'Namibia'),
    Country(129, 'North Macedonia'),
    Country(130, 'Nauru'),
    Country(131, 'Oman'),
    Country(132, 'Pakistan'),
    Country(133, 'Philippines'),
    Country(134, 'Poland'),
    Country(135, 'Peru'),
    Country(136, 'Portugal'),
    Country(137, 'Papua New Guinea'),
    Country(138, 'Paraguay'),
    Country(139, 'Palestine State'),
    Country(140, 'Panama'),
    Country(141, 'Palau'),
    Country(142, 'Qatar'),
    Country(143, 'Russia'),
    Country(144, 'Romania'),
    Country(145, 'Rwanda'),
    Country(146, 'South Africa'),
    Country(147, 'South Korea'),
    Country(148, 'Spain'),
    Country(149, 'Sudan'),
    Country(150, 'Saudi Arabia'),
    Country(151, 'Sri Lanka'),
    Country(152, 'Syria'),
    Country(153, 'Senegal'),
    Country(154, 'Somalia'),
    Country(155, 'South Sudan'),
    Country(156, 'Sweden'),
    Country(157, 'Serbia'),
    Country(158, 'Switzerland'),
    Country(159, 'Sierra Leone'),
    Country(160, 'Singapore'),
    Country(161, 'Slovakia'),
    Country(162, 'Slovenia'),
    Country(163, 'Solomon Islands'),
    Country(164, 'Suriname'),
    Country(165, 'Sao Tome and Principe'),
    Country(166, 'Samoa'),
    Country(167, 'Saint Lucia'),
    Country(168, 'Saint Vincent and the Grenadines'),
    Country(169, 'Seychelles'),
    Country(170, 'Saint Kitts and Nevis'),
    Country(171, 'San Marino'),
    Country(172, 'Turkey'),
    Country(173, 'Thailand'),
    Country(174, 'Tanzania'),
    Country(175, 'Tunisia'),
    Country(176, 'Tajikistan'),
    Country(177, 'Togo'),
    Country(178, 'Turkmenistan'),
    Country(179, 'Trinidad and Tobago'),
    Country(180, 'Timor-Leste'),
    Country(181, 'Tonga'),
    Country(182, 'Tuvalu'),
    Country(183, 'United States of America'),
    Country(184, 'United Kingdom'),
    Country(185, 'Uganda'),
    Country(186, 'Ukraine'),
    Country(187, 'Uzbekistan'),
    Country(188, 'United Arab Emirates'),
    Country(189, 'Uruguay'),
    Country(190, 'Vietnam'),
    Country(191, 'Venezuela'),
    Country(192, 'Vanuatu'),
    Country(193, 'Yemen'),
    Country(194, 'Zambia'),
    Country(195, 'Zimbabwe'),
  ];

  Stream<List<Country>> get filteredData => _filteredData.stream;

  HomeBloc() {
    _filteredData.add(dataList);
  }

  @override
  get onDataFiltered => _filteredData.add;

  @override
  get data => dataList;

  @override
  void dispose() {
    _filteredData.close();
    super.dispose();
  }
}
